liste_educative = [
    "Algèbre linéaire",
    "Théorie des nombres",
    "Équations différentielles",
    "Géométrie euclidienne",
    "Probabilités",
    "Statistiques",
    "Théorème de Pythagore",
    "Calcul intégral",
    "Calcul matriciel",
    "Chimie organique",
    "Chimie inorganique",
    "Biologie cellulaire",
    "Évolution",
    "Écologie",
    "Réaction chimique",
    "Photosynthèse",
    "Mécanique classique",
    "Électricité et magnétisme",
    "Thermodynamique",
    "Optique",
    "Mécanique quantique",
    "Relativité restreinte",
    "Physique nucléaire",
    "Histoire de l'art",
    "Littérature française",
    "Grammaire",
    "Orthographe",
    "Poésie",
    "Roman",
    "Philosophie",
    "Histoire mondiale",
    "Histoire de la France",
    "Révolution française",
    "Géographie physique",
    "Climatologie",
    "Économie",
    "Psychologie",
    "Sociologie",
    "Anthropologie",
    "Archéologie",
    "Langue étrangère",
    "Étude des langues",
    "Linguistique",
    "Astrophysique",
    "Astronomie",
    "Planètes du système solaire",
    "Étoiles et constellations",
    "Biologie moléculaire",
    "Génétique",

    ]

after=[
    "Système immunitaire",
    "Neurosciences",
    "Psychologie du développement",
    "Zoologie",
    "Botanique",
    "Géologie",
    "Paléontologie",
    "Écosystèmes marins",
    "Écosystèmes terrestres",
    "Cinématographie",
    "Théâtre",
    "Musique classique",
    "Musique contemporaine",
    "Art contemporain",
    "Droit international",
    "Droit constitutionnel",
    "Droit pénal",
    "Droit des contrats",
    "Éthique professionnelle",
    "Informatique",
    "Programmation",
    "Sécurité informatique",
    "Intelligence artificielle",
    "Réseaux informatiques",
    "Conception de sites web",
    "Énergie renouvelable",
    "Gestion de projet",
    "Marketing",
    "Éthique des affaires",
    "Médecine",
    "Anatomie",
    "Physiologie",
    "Pharmacologie",
    "Chirurgie",
    "Médecine alternative",
    "Psychiatrie",
    "Éthique médicale",
    "Éducation physique",
    "Nutrition",
    "Psychologie sportive",
    "Étude des médias",
    "Journalisme",
    "Communication interpersonnelle",
    "Relations publiques",
    "Éducation à l'environnement",
    "Éducation sexuelle",
    "Éducation financière",
    "Éducation artistique",
    "Éducation civique",
    "Éducation à la paix",
    "Éducation interculturelle",
    "Éducation à la santé",
    "Éducation à la technologie",
    "Éducation à l'éthique",
    "Éducation aux droits de l'homme",
    "Éducation à la citoyenneté",
    "Éducation à la diversité",
    "Éducation aux médias",
    "Éducation à la sécurité en ligne",
    "Éducation aux sciences sociales",
    "Éducation à la géographie",
    "Théorie de l'évolution",
    "Calcul intégral",
    "Révolution française",
    "Chimie organique",
    "Le romantisme",
    "Équations différentielles",
    "Révolution industrielle",
    "Mécanique quantique",
    "Analyse littéraire",
    "Géométrie euclidienne",
    "Renaissance artistique",
    "Lois de Newton",
    "Révolution américaine",
    "Langue française",
    "Électromagnétisme",
    "Révolution russe",
    "Littérature française du XIXe siècle",
    "Théorème de Pythagore",
    "Révolution chinoise",
    "L'œuvre de Shakespeare",
    "Physique nucléaire",
    "Moyen Âge européen",
    "Langue anglaise",
    "Équations de Maxwell",
    "Révolution cubaine",
    "L'Antiquité grecque",
    "Histoire de l'art",
    "Mécanique classique",
    "Histoire de la psychologie",
    "Géométrie non euclidienne",
    "Révolution mexicaine",
    "L'Antiquité romaine",
    "Linguistique",
    "Thermodynamique",
    "Révolution haïtienne",
    "La philosophie des Lumières",
    "Théorie de la relativité",
    "Révolution sud-africaine",
    "Littérature russe",
    "Biologie moléculaire",
    "La Renaissance",
    "Chimie inorganique",
    "Révolution indienne",
    "Littérature américaine",
    "Psychologie cognitive",
    "Théorie des ensembles",
    "Révolution iranienne",
    "Histoire de la musique",
    "Mécanique des fluides",
    "Révolution égyptienne",
    "Littérature hispanique",
    "Sociologie",
    "Théorie des graphes",
    "Révolution hongroise",
    "Art contemporain",
    "Physique des particules",
    "Révolution bolivienne",
    "Philosophie politique",
    "Algèbre linéaire",
    "Révolution algérienne",
    "Histoire de la danse",
    "Astronomie",
    "Révolution syrienne",
    "Littérature asiatique",
    "Économie",
    "Théorie des nombres",
    "Révolution vénézuélienne",
    "Philosophie de l'éducation",
    "Chimie physique",
    "Révolution ukrainienne",
    "Histoire de la mode",
    "Psychologie sociale",
    "Géologie",
    "Révolution libyenne",
    "Littérature africaine",
    "Philosophie de la science",
    "Biologie cellulaire",
    "Révolution turque",
    "Histoire du cinéma",
    "Neurosciences",
    "Chimie analytique",
    "Révolution soudanaise",
    "Littérature indienne",
    "Éthique",
    "Écologie",
    "Révolution marocaine",
    "Histoire de la photographie",
    "Psychologie du développement",
    "Astronomie",
    "Révolution tunisienne",
    "Littérature japonaise",
    "Santé publique",
    "Théorie de la communication",
    "Biologie évolutive",
    "Chimie organique",
    "Révolution grecque",
    "Histoire de l'architecture",
    "Psychologie clinique",
    "Économie politique",
    "Génétique",
    "Révolution tchèque",
    "Littérature chinoise",
    "Éthique des affaires",
    "Informatique",
    "Physiologie",
    "Chimie inorganique",
    "Révolution portugaise",
    "Histoire de l'opéra",
    "Psychologie de la personnalité",
    "Finance",
    "Biologie marine",
    "Révolution philippine",
    "Littérature russe du XIXe siècle",
    "Anthropologie",
    "Théorie de l'information",
    "Biologie végétale",
    "Chimie analytique",
    "Révolution cambodgienne",
    "Histoire de la télévision",
    "Psychologie de la motivation",
    "Marketing",
    "Biologie animale",
    "Révolution népalaise",
    "Littérature latino-américaine",
    "Science politique",
    "Philosophie de la religion",
    "Biologie génétique",
    "Chimie des polymères",
    "Révolution birmane",
    "Histoire de l'art moderne",
    "Psychologie de la santé",
    "Entrepreneuriat",
    "Biologie cellulaire",
    "Révolution zimbabwéenne",
    "Littérature anglaise",
    "Économie internationale",
    "Philosophie de l'éthique",
    "Biologie moléculaire",
    "Chimie physique",
    "Révolution néo-zélandaise",
    "Histoire de la sculpture",
    "Psychologie industrielle",
    "Gestion des ressources humaines",
    "Biologie évolutive",
    "Chimie environnementale",
    "Révolution nicaraguayenne",
    "Littérature allemande",
    "Économie du développement",
    "Philosophie de l'art",
    "Biologie de l'évolution",
    "Chimie nucléaire",
    "Révolution guatémaltèque",
    "Histoire de la mode",
    "Psychologie de la cognition",
    "Gestion financière",
    "Biologie marine",
    "Chimie analytique",
    "Révolution croate",
    "Littérature italienne",
    "Économie de l'environnement",
    "Philosophie de la connaissance",
    "Biologie végétale",
    "Chimie des médicaments",
    "Révolution slovaque",
    "Histoire de la photographie",
    "Psychologie de l'apprentissage",
    "Marketing numérique",
    "Biologie animale",
    "Chimie des matériaux",
    "Révolution équatorienne",
    "Littérature espagnole",
    "Économie comportementale",
    "Philosophie de la technologie",
    "Biologie génétique",
    "Chimie des aliments",
    "Révolution lettonienne",
    "Histoire de l'art contemporain",
    "Psychologie sportive",
    "Gestion de projet",
    "Biologie cellulaire",
    "Chimie industrielle",
    "Révolution serbe",
    "Littérature française du XXe siècle",
    "Économie de la santé",
    "Philosophie de la politique",
    "Biologie moléculaire",
    "Chimie organique",
    "Révolution estonienne",
    "Histoire de la mode",
    "Psychologie positive",
    "Gestion des opérations",
    "Biologie évolutive",
    "Chimie environnementale",
    "Révolution géorgienne",
    "Littérature britannique",
    "Économie du travail",
    "Philosophie de l'histoire",
    "Biologie de l'évolution",
    "Chimie nucléaire",
    "Révolution ukrainienne",
    "Histoire de l'art médiéval",
    "Psychologie des émotions",
    "Gestion de la chaîne d'approvisionnement",
    "Biologie marine",
    "Chimie analytique",
    "Révolution slovène",
    "Littérature canadienne",
    "Économie de l'éducation",
    "Philosophie de la morale",
    "Biologie végétale",
    "Chimie des médicaments",
    "Révolution arménienne",
    "Histoire de l'opéra",
    "Psychologie du leadership",
    "Gestion de l'innovation",
    "Biologie animale",
    "Chimie des matériaux",
    "Révolution maltaise",
    "Littérature australienne",
    "Économie du développement durable",
    "Philosophie politique",
    "Biologie génétique",
    "Chimie des aliments",
    "Révolution moldave",
    "Histoire de la sculpture",
    "Psychologie des relations interpersonnelles",
    "Gestion de la qualité",
    "Biologie cellulaire",
    "Chimie industrielle",
    "Révolution kirghize",
    "Littérature africaine",
    "Économie comportementale",
    "Philosophie de la religion",
    "Biologie moléculaire",
    "Chimie organique",
    "Révolution tadjike",
    "Histoire de la mode",
    "Psychologie de la motivation",
    "Gestion des ressources humaines",
    "Biologie évolutive",
    "Chimie environnementale",
    "Révolution turkmène",
    "Littérature hispanique",
    "Économie internationale",
    "Philosophie de l'éthique",
    "Biologie de l'évolution",
    "Chimie nucléaire",
    "Révolution ouzbèke",
    "Histoire de la photographie",
    "Psychologie de l'apprentissage",
    "Marketing numérique",
    "Biologie animale",
    "Chimie des matériaux",
    "Révolution tibétaine",
    "Littérature italienne",
    "Économie de l'environnement",
    "Philosophie de la connaissance",
    "Biologie végétale",
    "Chimie des médicaments",
    "Révolution antillaise",
    "Histoire de l'art contemporain",
    "Psychologie sportive",
    "Gestion de projet",
    "Biologie cellulaire",
    "Chimie industrielle",
    "Révolution micronésienne",
    "Littérature française du XXe siècle",
    "Économie de la santé",
    "Philosophie de la politique",
    "Biologie moléculaire",
    "Chimie organique",
    "Révolution fidjienne",
    "Histoire de la mode",
    "Psychologie positive",
    "Gestion des opérations",
    "Biologie évolutive",
    "Chimie environnementale",
    "Révolution papouasienne",
    "Littérature britannique",
    "Économie du travail",
    "Philosophie de l'histoire",
    "Biologie de l'évolution",
    "Chimie nucléaire",
    "Révolution tuvaluane",
    "Histoire de l'art médiéval",
    "Psychologie des émotions",
    "Gestion de la chaîne d'approvisionnement",
    "Biologie marine",
    "Chimie analytique",
    "Révolution salomonienne",
    "Littérature canadienne",
    "Économie de l'éducation",
    "Philosophie de la morale",
    "Biologie végétale",
    "Chimie des médicaments",
    "Révolution tongienne",
    "Histoire de l'opéra",
    "Psychologie du leadership",
    "Gestion de l'innovation",
    "Biologie animale",
    "Chimie des matériaux",
    "Révolution samoane",
    "Littérature australienne",
    "Économie du développement durable",
    "Philosophie politique",
    "Biologie génétique",
    "Chimie des aliments",
    "Révolution kirghize",
    "Histoire de la sculpture",
    "Psychologie des relations interpersonnelles",
    "Gestion de la qualité",
    "Biologie cellulaire",
    "Chimie industrielle",
    "Révolution marshallaise",
    "Littérature africaine",
    "Économie comportementale",
    "Philosophie de la religion",
    "Biologie moléculaire",
    "Chimie organique",
    "Révolution paluane",
    "Histoire de la mode",
    "Psychologie de la motivation",
    "Gestion des ressources humaines",
    "Biologie évolutive",
    "Chimie environnementale",
    "Révolution niuéenne",
    "Littérature hispanique",
    "Économie internationale",
    "Philosophie de l'éthique",
    "Biologie de l'évolution",
    "Chimie nucléaire",
    "Histoire ancienne",
    "Histoire médiévale",
    "Histoire moderne",
    "Histoire contemporaine",
    "Géographie du monde",
    "Géographie physique",
    "Géographie humaine",
    "Géographie économique",
    "Géographie politique",
    "Géographie de la France",
    "Géographie de l'Europe",
    "Géographie de l'Asie",
    "Géographie de l'Afrique",
    "Géographie de l'Amérique du Nord",
    "Géographie de l'Amérique du Sud",
    "Géographie de l'Océanie",
    "Littérature française",
    "Littérature anglaise",
    "Littérature américaine",
    "Littérature russe",
    "Littérature japonaise",
    "Littérature classique",
    "Littérature contemporaine",
    "Philosophie occidentale",
    "Philosophie orientale",
    "Philosophie antique",
    "Philosophie moderne",
    "Philosophie contemporaine",
    "Mathématiques fondamentales",
"Métaphysique",
    "Épistémologie",
    "Éthique",
    "Morale",
    "Logique",
    "Phénoménologie",
    "Existentialisme",
    "Rationalisme",
    "Empirisme",
    "Positivisme",
    "Idéalisme",
    "Matérialisme",
    "Scepticisme",
    "Hédonisme",
    "Utilitarisme",
    "Éthique de la vertu",
    "Libertarianisme",
    "Déontologie",
    "Égoïsme",
    "Absolutisme moral",
    "Contrat social",
    "Réalisme métaphysique",
    "Nihilisme",
    "Dualisme",
    "Monisme",
    "Solipsisme",
    "Phénomène",
    "Noumène",
    "Cogito, ergo sum",
    "Dialectique",

]

